### ISSUE TITLE
Not receiving from morsecode.tools

### ISSUE THREAD

**Issue by sime** [ggerganov/ggmorse#3]
Hi!

Saw you post on HackerNews, and only now got the time to respond.

I too have a tiny PWA for transmitting Morse Code: https://morsecode.tools/

Haven't had much luck transmitting to your webapp. I see you transmit at 550 Hz, though setting that on my side I didn't have any luck. Any tips?

Also, I noticed when transmitting on the webapp on a mobile, the on-screen keyboard does not appear for both Firefox and Chrome.

**Comment by ggerganov** [comment]
Hi,

I just tried using your tool and it seems to work OK with GGMorse webapp.
Here is a short video demonstration (enable sound):

https://user-images.githubusercontent.com/1991296/128624314-9bca1f73-9575-40f5-aa6e-0b4fb2b31d29.mp4

I think there is something off in the timing of your transmission - the pause between letters should be 3 dots, but I think your tool produces a longer pause. Not sure though, need to look in more details.

Regarding the on-screen keyboard problem when using the webapp on mobile:
Yes, unfortunately I haven't been able to figure out how to show it. The problem is that this is a custom SDL2 application ported to the Web using Emscripten/WASM and there seems to be no trivial way to open the device's keyboard when I want to.

**Comment by sime** [comment]
Took in your feedback, works like a charm :)

Here is the PR: https://github.com/sime/morse-transmitter/pull/6
